# Generated by Django 5.1 on 2024-08-13 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fech_nacimiento',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
    ]
